service: node-rest-mongoose

provider:
  name: aws
  runtime: nodejs10.x

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

functions:
  createPhoto:
    handler: handler.createPhoto
    events:
      - http:
          path: user/{id}/photo
          method: post
          cors: true

  updatePhoto:
    handler: handler.updatePhoto
    events:
      - http:
          path: user/{id}/photo/{id}
          method: put
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}/photo/{id}
          method: get
          cors: true
