service: node-rest-mongoose

provider:
  name: aws
  runtime: nodejs10.x

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  createPhoto:
    handler: handler.user.createPhoto
    events:
      - http:
          path: user/{id}/photo
          method: post
          cors: true

  updatePhoto:
    handler: handler.user.updatePhoto
    events:
      - http:
          path: user/{id}/photo/{id}
          method: put
          cors: true

  photo:
    handler: handler.user.photo
    events:
      - http:
          path: user/{id}/photo/{id}
          method: get
          cors: true

  createAproval:
    handler: handler.user.createAproval
    events:
      - http:
          path: user/{id}/aproval
          method: post
          cors: true

  updateAproval:
    handler: handler.user.updateAproval
    events:
      - http:
          path: user/{id}/aproval/{id}
          method: put
          cors: true

  aproval:
    handler: handler.user.aproval
    events:
      - http:
          path: user/{id}/aproval/{id}
          method: get
          cors: true
